/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { CardButton, MenuOption, Message, MessagePart, ThinkingStep } from "./types";
export { CardButton, MenuOption, Message, MessagePart, ThinkingStep } from "./types";
export namespace Components {
    interface SmcChatWidget {
        "apiUrl"?: string;
        "mockConfig"?: string;
        /**
          * When set, the widget streams from the mock transport using this scenario key (thinking | menu | files | image | error) instead of the real backend.
         */
        "mockScenario"?: string;
        "sdkId": string;
    }
    interface SmcChatWindow {
    }
    interface SmcCsatSurvey {
    }
    interface SmcFeedback {
        "messageId": string;
    }
    interface SmcFilePreview {
        "fileName": string;
        "fileSize": number;
        "fileUrl": string;
        "mimeType": string;
    }
    interface SmcHeader {
    }
    interface SmcInputBar {
    }
    interface SmcKbSuggestions {
    }
    interface SmcLauncher {
    }
    interface SmcMarkdown {
        "content": string;
    }
    interface SmcMessage {
        "message": Message;
        /**
          * @default false
         */
        "showFeedback": boolean;
    }
    interface SmcMessageList {
    }
    interface SmcMessagePart {
        "partData": MessagePart;
    }
    interface SmcPartCard {
        "partData": { type: 'card'; title: string; description?: string; buttons?: CardButton[] };
    }
    interface SmcPartFile {
        "partData": { type: 'file'; name: string; mimeType: string; url: string; sizeBytes?: number };
    }
    interface SmcPartImage {
        "partData": { type: 'image'; url: string; alt?: string };
    }
    interface SmcPartMenu {
        "partData": { type: 'menu'; title?: string; options: MenuOption[] };
    }
    interface SmcPartText {
        "partData": { type: 'text'; text: string };
    }
    interface SmcPartThinking {
        "partData": { type: 'thinking'; status: 'active' | 'done'; steps: ThinkingStep[] };
    }
    interface SmcPreChatForm {
    }
    interface SmcProactiveEngine {
    }
    interface SmcQuickReplies {
    }
    interface SmcTimestamp {
        "timestamp": string;
    }
    interface SmcTypingIndicator {
    }
}
export interface SmcMessageCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSmcMessageElement;
}
export interface SmcPartCardCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSmcPartCardElement;
}
export interface SmcPartMenuCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSmcPartMenuElement;
}
export interface SmcQuickRepliesCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSmcQuickRepliesElement;
}
declare global {
    interface HTMLSmcChatWidgetElement extends Components.SmcChatWidget, HTMLStencilElement {
    }
    var HTMLSmcChatWidgetElement: {
        prototype: HTMLSmcChatWidgetElement;
        new (): HTMLSmcChatWidgetElement;
    };
    interface HTMLSmcChatWindowElement extends Components.SmcChatWindow, HTMLStencilElement {
    }
    var HTMLSmcChatWindowElement: {
        prototype: HTMLSmcChatWindowElement;
        new (): HTMLSmcChatWindowElement;
    };
    interface HTMLSmcCsatSurveyElement extends Components.SmcCsatSurvey, HTMLStencilElement {
    }
    var HTMLSmcCsatSurveyElement: {
        prototype: HTMLSmcCsatSurveyElement;
        new (): HTMLSmcCsatSurveyElement;
    };
    interface HTMLSmcFeedbackElement extends Components.SmcFeedback, HTMLStencilElement {
    }
    var HTMLSmcFeedbackElement: {
        prototype: HTMLSmcFeedbackElement;
        new (): HTMLSmcFeedbackElement;
    };
    interface HTMLSmcFilePreviewElement extends Components.SmcFilePreview, HTMLStencilElement {
    }
    var HTMLSmcFilePreviewElement: {
        prototype: HTMLSmcFilePreviewElement;
        new (): HTMLSmcFilePreviewElement;
    };
    interface HTMLSmcHeaderElement extends Components.SmcHeader, HTMLStencilElement {
    }
    var HTMLSmcHeaderElement: {
        prototype: HTMLSmcHeaderElement;
        new (): HTMLSmcHeaderElement;
    };
    interface HTMLSmcInputBarElement extends Components.SmcInputBar, HTMLStencilElement {
    }
    var HTMLSmcInputBarElement: {
        prototype: HTMLSmcInputBarElement;
        new (): HTMLSmcInputBarElement;
    };
    interface HTMLSmcKbSuggestionsElement extends Components.SmcKbSuggestions, HTMLStencilElement {
    }
    var HTMLSmcKbSuggestionsElement: {
        prototype: HTMLSmcKbSuggestionsElement;
        new (): HTMLSmcKbSuggestionsElement;
    };
    interface HTMLSmcLauncherElement extends Components.SmcLauncher, HTMLStencilElement {
    }
    var HTMLSmcLauncherElement: {
        prototype: HTMLSmcLauncherElement;
        new (): HTMLSmcLauncherElement;
    };
    interface HTMLSmcMarkdownElement extends Components.SmcMarkdown, HTMLStencilElement {
    }
    var HTMLSmcMarkdownElement: {
        prototype: HTMLSmcMarkdownElement;
        new (): HTMLSmcMarkdownElement;
    };
    interface HTMLSmcMessageElementEventMap {
        "messageRetry": string;
    }
    interface HTMLSmcMessageElement extends Components.SmcMessage, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSmcMessageElementEventMap>(type: K, listener: (this: HTMLSmcMessageElement, ev: SmcMessageCustomEvent<HTMLSmcMessageElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSmcMessageElementEventMap>(type: K, listener: (this: HTMLSmcMessageElement, ev: SmcMessageCustomEvent<HTMLSmcMessageElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSmcMessageElement: {
        prototype: HTMLSmcMessageElement;
        new (): HTMLSmcMessageElement;
    };
    interface HTMLSmcMessageListElement extends Components.SmcMessageList, HTMLStencilElement {
    }
    var HTMLSmcMessageListElement: {
        prototype: HTMLSmcMessageListElement;
        new (): HTMLSmcMessageListElement;
    };
    interface HTMLSmcMessagePartElement extends Components.SmcMessagePart, HTMLStencilElement {
    }
    var HTMLSmcMessagePartElement: {
        prototype: HTMLSmcMessagePartElement;
        new (): HTMLSmcMessagePartElement;
    };
    interface HTMLSmcPartCardElementEventMap {
        "cardAction": string;
    }
    interface HTMLSmcPartCardElement extends Components.SmcPartCard, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSmcPartCardElementEventMap>(type: K, listener: (this: HTMLSmcPartCardElement, ev: SmcPartCardCustomEvent<HTMLSmcPartCardElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSmcPartCardElementEventMap>(type: K, listener: (this: HTMLSmcPartCardElement, ev: SmcPartCardCustomEvent<HTMLSmcPartCardElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSmcPartCardElement: {
        prototype: HTMLSmcPartCardElement;
        new (): HTMLSmcPartCardElement;
    };
    interface HTMLSmcPartFileElement extends Components.SmcPartFile, HTMLStencilElement {
    }
    var HTMLSmcPartFileElement: {
        prototype: HTMLSmcPartFileElement;
        new (): HTMLSmcPartFileElement;
    };
    interface HTMLSmcPartImageElement extends Components.SmcPartImage, HTMLStencilElement {
    }
    var HTMLSmcPartImageElement: {
        prototype: HTMLSmcPartImageElement;
        new (): HTMLSmcPartImageElement;
    };
    interface HTMLSmcPartMenuElementEventMap {
        "menuSelect": string;
    }
    interface HTMLSmcPartMenuElement extends Components.SmcPartMenu, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSmcPartMenuElementEventMap>(type: K, listener: (this: HTMLSmcPartMenuElement, ev: SmcPartMenuCustomEvent<HTMLSmcPartMenuElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSmcPartMenuElementEventMap>(type: K, listener: (this: HTMLSmcPartMenuElement, ev: SmcPartMenuCustomEvent<HTMLSmcPartMenuElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSmcPartMenuElement: {
        prototype: HTMLSmcPartMenuElement;
        new (): HTMLSmcPartMenuElement;
    };
    interface HTMLSmcPartTextElement extends Components.SmcPartText, HTMLStencilElement {
    }
    var HTMLSmcPartTextElement: {
        prototype: HTMLSmcPartTextElement;
        new (): HTMLSmcPartTextElement;
    };
    interface HTMLSmcPartThinkingElement extends Components.SmcPartThinking, HTMLStencilElement {
    }
    var HTMLSmcPartThinkingElement: {
        prototype: HTMLSmcPartThinkingElement;
        new (): HTMLSmcPartThinkingElement;
    };
    interface HTMLSmcPreChatFormElement extends Components.SmcPreChatForm, HTMLStencilElement {
    }
    var HTMLSmcPreChatFormElement: {
        prototype: HTMLSmcPreChatFormElement;
        new (): HTMLSmcPreChatFormElement;
    };
    interface HTMLSmcProactiveEngineElement extends Components.SmcProactiveEngine, HTMLStencilElement {
    }
    var HTMLSmcProactiveEngineElement: {
        prototype: HTMLSmcProactiveEngineElement;
        new (): HTMLSmcProactiveEngineElement;
    };
    interface HTMLSmcQuickRepliesElementEventMap {
        "smcQuickReply": { text: string };
    }
    interface HTMLSmcQuickRepliesElement extends Components.SmcQuickReplies, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSmcQuickRepliesElementEventMap>(type: K, listener: (this: HTMLSmcQuickRepliesElement, ev: SmcQuickRepliesCustomEvent<HTMLSmcQuickRepliesElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSmcQuickRepliesElementEventMap>(type: K, listener: (this: HTMLSmcQuickRepliesElement, ev: SmcQuickRepliesCustomEvent<HTMLSmcQuickRepliesElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSmcQuickRepliesElement: {
        prototype: HTMLSmcQuickRepliesElement;
        new (): HTMLSmcQuickRepliesElement;
    };
    interface HTMLSmcTimestampElement extends Components.SmcTimestamp, HTMLStencilElement {
    }
    var HTMLSmcTimestampElement: {
        prototype: HTMLSmcTimestampElement;
        new (): HTMLSmcTimestampElement;
    };
    interface HTMLSmcTypingIndicatorElement extends Components.SmcTypingIndicator, HTMLStencilElement {
    }
    var HTMLSmcTypingIndicatorElement: {
        prototype: HTMLSmcTypingIndicatorElement;
        new (): HTMLSmcTypingIndicatorElement;
    };
    interface HTMLElementTagNameMap {
        "smc-chat-widget": HTMLSmcChatWidgetElement;
        "smc-chat-window": HTMLSmcChatWindowElement;
        "smc-csat-survey": HTMLSmcCsatSurveyElement;
        "smc-feedback": HTMLSmcFeedbackElement;
        "smc-file-preview": HTMLSmcFilePreviewElement;
        "smc-header": HTMLSmcHeaderElement;
        "smc-input-bar": HTMLSmcInputBarElement;
        "smc-kb-suggestions": HTMLSmcKbSuggestionsElement;
        "smc-launcher": HTMLSmcLauncherElement;
        "smc-markdown": HTMLSmcMarkdownElement;
        "smc-message": HTMLSmcMessageElement;
        "smc-message-list": HTMLSmcMessageListElement;
        "smc-message-part": HTMLSmcMessagePartElement;
        "smc-part-card": HTMLSmcPartCardElement;
        "smc-part-file": HTMLSmcPartFileElement;
        "smc-part-image": HTMLSmcPartImageElement;
        "smc-part-menu": HTMLSmcPartMenuElement;
        "smc-part-text": HTMLSmcPartTextElement;
        "smc-part-thinking": HTMLSmcPartThinkingElement;
        "smc-pre-chat-form": HTMLSmcPreChatFormElement;
        "smc-proactive-engine": HTMLSmcProactiveEngineElement;
        "smc-quick-replies": HTMLSmcQuickRepliesElement;
        "smc-timestamp": HTMLSmcTimestampElement;
        "smc-typing-indicator": HTMLSmcTypingIndicatorElement;
    }
}
declare namespace LocalJSX {
    type OneOf<K extends string, PropT, AttrT = PropT> = { [P in K]: PropT } & { [P in `attr:${K}` | `prop:${K}`]?: never } | { [P in `attr:${K}`]: AttrT } & { [P in K | `prop:${K}`]?: never } | { [P in `prop:${K}`]: PropT } & { [P in K | `attr:${K}`]?: never };

    interface SmcChatWidget {
        "apiUrl"?: string;
        "mockConfig"?: string;
        /**
          * When set, the widget streams from the mock transport using this scenario key (thinking | menu | files | image | error) instead of the real backend.
         */
        "mockScenario"?: string;
        "sdkId": string;
    }
    interface SmcChatWindow {
    }
    interface SmcCsatSurvey {
    }
    interface SmcFeedback {
        "messageId": string;
    }
    interface SmcFilePreview {
        "fileName": string;
        "fileSize": number;
        "fileUrl": string;
        "mimeType": string;
    }
    interface SmcHeader {
    }
    interface SmcInputBar {
    }
    interface SmcKbSuggestions {
    }
    interface SmcLauncher {
    }
    interface SmcMarkdown {
        "content": string;
    }
    interface SmcMessage {
        "message": Message;
        "onMessageRetry"?: (event: SmcMessageCustomEvent<string>) => void;
        /**
          * @default false
         */
        "showFeedback"?: boolean;
    }
    interface SmcMessageList {
    }
    interface SmcMessagePart {
        "partData": MessagePart;
    }
    interface SmcPartCard {
        "onCardAction"?: (event: SmcPartCardCustomEvent<string>) => void;
        "partData": { type: 'card'; title: string; description?: string; buttons?: CardButton[] };
    }
    interface SmcPartFile {
        "partData": { type: 'file'; name: string; mimeType: string; url: string; sizeBytes?: number };
    }
    interface SmcPartImage {
        "partData": { type: 'image'; url: string; alt?: string };
    }
    interface SmcPartMenu {
        "onMenuSelect"?: (event: SmcPartMenuCustomEvent<string>) => void;
        "partData": { type: 'menu'; title?: string; options: MenuOption[] };
    }
    interface SmcPartText {
        "partData": { type: 'text'; text: string };
    }
    interface SmcPartThinking {
        "partData": { type: 'thinking'; status: 'active' | 'done'; steps: ThinkingStep[] };
    }
    interface SmcPreChatForm {
    }
    interface SmcProactiveEngine {
    }
    interface SmcQuickReplies {
        "onSmcQuickReply"?: (event: SmcQuickRepliesCustomEvent<{ text: string }>) => void;
    }
    interface SmcTimestamp {
        "timestamp": string;
    }
    interface SmcTypingIndicator {
    }

    interface SmcChatWidgetAttributes {
        "sdkId": string;
        "apiUrl": string;
        "mockConfig": string;
        "mockScenario": string;
    }
    interface SmcFeedbackAttributes {
        "messageId": string;
    }
    interface SmcFilePreviewAttributes {
        "fileName": string;
        "fileUrl": string;
        "mimeType": string;
        "fileSize": number;
    }
    interface SmcMarkdownAttributes {
        "content": string;
    }
    interface SmcMessageAttributes {
        "showFeedback": boolean;
    }
    interface SmcTimestampAttributes {
        "timestamp": string;
    }

    interface IntrinsicElements {
        "smc-chat-widget": Omit<SmcChatWidget, keyof SmcChatWidgetAttributes> & { [K in keyof SmcChatWidget & keyof SmcChatWidgetAttributes]?: SmcChatWidget[K] } & { [K in keyof SmcChatWidget & keyof SmcChatWidgetAttributes as `attr:${K}`]?: SmcChatWidgetAttributes[K] } & { [K in keyof SmcChatWidget & keyof SmcChatWidgetAttributes as `prop:${K}`]?: SmcChatWidget[K] } & OneOf<"sdkId", SmcChatWidget["sdkId"], SmcChatWidgetAttributes["sdkId"]>;
        "smc-chat-window": SmcChatWindow;
        "smc-csat-survey": SmcCsatSurvey;
        "smc-feedback": Omit<SmcFeedback, keyof SmcFeedbackAttributes> & { [K in keyof SmcFeedback & keyof SmcFeedbackAttributes]?: SmcFeedback[K] } & { [K in keyof SmcFeedback & keyof SmcFeedbackAttributes as `attr:${K}`]?: SmcFeedbackAttributes[K] } & { [K in keyof SmcFeedback & keyof SmcFeedbackAttributes as `prop:${K}`]?: SmcFeedback[K] } & OneOf<"messageId", SmcFeedback["messageId"], SmcFeedbackAttributes["messageId"]>;
        "smc-file-preview": Omit<SmcFilePreview, keyof SmcFilePreviewAttributes> & { [K in keyof SmcFilePreview & keyof SmcFilePreviewAttributes]?: SmcFilePreview[K] } & { [K in keyof SmcFilePreview & keyof SmcFilePreviewAttributes as `attr:${K}`]?: SmcFilePreviewAttributes[K] } & { [K in keyof SmcFilePreview & keyof SmcFilePreviewAttributes as `prop:${K}`]?: SmcFilePreview[K] } & OneOf<"fileName", SmcFilePreview["fileName"], SmcFilePreviewAttributes["fileName"]> & OneOf<"fileUrl", SmcFilePreview["fileUrl"], SmcFilePreviewAttributes["fileUrl"]> & OneOf<"mimeType", SmcFilePreview["mimeType"], SmcFilePreviewAttributes["mimeType"]> & OneOf<"fileSize", SmcFilePreview["fileSize"], SmcFilePreviewAttributes["fileSize"]>;
        "smc-header": SmcHeader;
        "smc-input-bar": SmcInputBar;
        "smc-kb-suggestions": SmcKbSuggestions;
        "smc-launcher": SmcLauncher;
        "smc-markdown": Omit<SmcMarkdown, keyof SmcMarkdownAttributes> & { [K in keyof SmcMarkdown & keyof SmcMarkdownAttributes]?: SmcMarkdown[K] } & { [K in keyof SmcMarkdown & keyof SmcMarkdownAttributes as `attr:${K}`]?: SmcMarkdownAttributes[K] } & { [K in keyof SmcMarkdown & keyof SmcMarkdownAttributes as `prop:${K}`]?: SmcMarkdown[K] } & OneOf<"content", SmcMarkdown["content"], SmcMarkdownAttributes["content"]>;
        "smc-message": Omit<SmcMessage, keyof SmcMessageAttributes> & { [K in keyof SmcMessage & keyof SmcMessageAttributes]?: SmcMessage[K] } & { [K in keyof SmcMessage & keyof SmcMessageAttributes as `attr:${K}`]?: SmcMessageAttributes[K] } & { [K in keyof SmcMessage & keyof SmcMessageAttributes as `prop:${K}`]?: SmcMessage[K] };
        "smc-message-list": SmcMessageList;
        "smc-message-part": SmcMessagePart;
        "smc-part-card": SmcPartCard;
        "smc-part-file": SmcPartFile;
        "smc-part-image": SmcPartImage;
        "smc-part-menu": SmcPartMenu;
        "smc-part-text": SmcPartText;
        "smc-part-thinking": SmcPartThinking;
        "smc-pre-chat-form": SmcPreChatForm;
        "smc-proactive-engine": SmcProactiveEngine;
        "smc-quick-replies": SmcQuickReplies;
        "smc-timestamp": Omit<SmcTimestamp, keyof SmcTimestampAttributes> & { [K in keyof SmcTimestamp & keyof SmcTimestampAttributes]?: SmcTimestamp[K] } & { [K in keyof SmcTimestamp & keyof SmcTimestampAttributes as `attr:${K}`]?: SmcTimestampAttributes[K] } & { [K in keyof SmcTimestamp & keyof SmcTimestampAttributes as `prop:${K}`]?: SmcTimestamp[K] } & OneOf<"timestamp", SmcTimestamp["timestamp"], SmcTimestampAttributes["timestamp"]>;
        "smc-typing-indicator": SmcTypingIndicator;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "smc-chat-widget": LocalJSX.IntrinsicElements["smc-chat-widget"] & JSXBase.HTMLAttributes<HTMLSmcChatWidgetElement>;
            "smc-chat-window": LocalJSX.IntrinsicElements["smc-chat-window"] & JSXBase.HTMLAttributes<HTMLSmcChatWindowElement>;
            "smc-csat-survey": LocalJSX.IntrinsicElements["smc-csat-survey"] & JSXBase.HTMLAttributes<HTMLSmcCsatSurveyElement>;
            "smc-feedback": LocalJSX.IntrinsicElements["smc-feedback"] & JSXBase.HTMLAttributes<HTMLSmcFeedbackElement>;
            "smc-file-preview": LocalJSX.IntrinsicElements["smc-file-preview"] & JSXBase.HTMLAttributes<HTMLSmcFilePreviewElement>;
            "smc-header": LocalJSX.IntrinsicElements["smc-header"] & JSXBase.HTMLAttributes<HTMLSmcHeaderElement>;
            "smc-input-bar": LocalJSX.IntrinsicElements["smc-input-bar"] & JSXBase.HTMLAttributes<HTMLSmcInputBarElement>;
            "smc-kb-suggestions": LocalJSX.IntrinsicElements["smc-kb-suggestions"] & JSXBase.HTMLAttributes<HTMLSmcKbSuggestionsElement>;
            "smc-launcher": LocalJSX.IntrinsicElements["smc-launcher"] & JSXBase.HTMLAttributes<HTMLSmcLauncherElement>;
            "smc-markdown": LocalJSX.IntrinsicElements["smc-markdown"] & JSXBase.HTMLAttributes<HTMLSmcMarkdownElement>;
            "smc-message": LocalJSX.IntrinsicElements["smc-message"] & JSXBase.HTMLAttributes<HTMLSmcMessageElement>;
            "smc-message-list": LocalJSX.IntrinsicElements["smc-message-list"] & JSXBase.HTMLAttributes<HTMLSmcMessageListElement>;
            "smc-message-part": LocalJSX.IntrinsicElements["smc-message-part"] & JSXBase.HTMLAttributes<HTMLSmcMessagePartElement>;
            "smc-part-card": LocalJSX.IntrinsicElements["smc-part-card"] & JSXBase.HTMLAttributes<HTMLSmcPartCardElement>;
            "smc-part-file": LocalJSX.IntrinsicElements["smc-part-file"] & JSXBase.HTMLAttributes<HTMLSmcPartFileElement>;
            "smc-part-image": LocalJSX.IntrinsicElements["smc-part-image"] & JSXBase.HTMLAttributes<HTMLSmcPartImageElement>;
            "smc-part-menu": LocalJSX.IntrinsicElements["smc-part-menu"] & JSXBase.HTMLAttributes<HTMLSmcPartMenuElement>;
            "smc-part-text": LocalJSX.IntrinsicElements["smc-part-text"] & JSXBase.HTMLAttributes<HTMLSmcPartTextElement>;
            "smc-part-thinking": LocalJSX.IntrinsicElements["smc-part-thinking"] & JSXBase.HTMLAttributes<HTMLSmcPartThinkingElement>;
            "smc-pre-chat-form": LocalJSX.IntrinsicElements["smc-pre-chat-form"] & JSXBase.HTMLAttributes<HTMLSmcPreChatFormElement>;
            "smc-proactive-engine": LocalJSX.IntrinsicElements["smc-proactive-engine"] & JSXBase.HTMLAttributes<HTMLSmcProactiveEngineElement>;
            "smc-quick-replies": LocalJSX.IntrinsicElements["smc-quick-replies"] & JSXBase.HTMLAttributes<HTMLSmcQuickRepliesElement>;
            "smc-timestamp": LocalJSX.IntrinsicElements["smc-timestamp"] & JSXBase.HTMLAttributes<HTMLSmcTimestampElement>;
            "smc-typing-indicator": LocalJSX.IntrinsicElements["smc-typing-indicator"] & JSXBase.HTMLAttributes<HTMLSmcTypingIndicatorElement>;
        }
    }
}
