/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SmcChatWidget {
        "apiUrl"?: string;
        "sdkId": string;
    }
    interface SmcChatWindow {
    }
    interface SmcFeedback {
        "messageId": string;
    }
    interface SmcHeader {
    }
    interface SmcInputBar {
    }
    interface SmcLauncher {
    }
    interface SmcMarkdown {
        "content": string;
    }
    interface SmcMessage {
        "content": string;
        "messageId": string;
        "role": 'user' | 'assistant';
        "status"?: string;
        "timestamp": string;
    }
    interface SmcMessageList {
    }
    interface SmcPreChatForm {
    }
    interface SmcQuickReplies {
    }
    interface SmcTimestamp {
        "timestamp": string;
    }
    interface SmcTypingIndicator {
    }
}
export interface SmcQuickRepliesCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSmcQuickRepliesElement;
}
declare global {
    interface HTMLSmcChatWidgetElement extends Components.SmcChatWidget, HTMLStencilElement {
    }
    var HTMLSmcChatWidgetElement: {
        prototype: HTMLSmcChatWidgetElement;
        new (): HTMLSmcChatWidgetElement;
    };
    interface HTMLSmcChatWindowElement extends Components.SmcChatWindow, HTMLStencilElement {
    }
    var HTMLSmcChatWindowElement: {
        prototype: HTMLSmcChatWindowElement;
        new (): HTMLSmcChatWindowElement;
    };
    interface HTMLSmcFeedbackElement extends Components.SmcFeedback, HTMLStencilElement {
    }
    var HTMLSmcFeedbackElement: {
        prototype: HTMLSmcFeedbackElement;
        new (): HTMLSmcFeedbackElement;
    };
    interface HTMLSmcHeaderElement extends Components.SmcHeader, HTMLStencilElement {
    }
    var HTMLSmcHeaderElement: {
        prototype: HTMLSmcHeaderElement;
        new (): HTMLSmcHeaderElement;
    };
    interface HTMLSmcInputBarElement extends Components.SmcInputBar, HTMLStencilElement {
    }
    var HTMLSmcInputBarElement: {
        prototype: HTMLSmcInputBarElement;
        new (): HTMLSmcInputBarElement;
    };
    interface HTMLSmcLauncherElement extends Components.SmcLauncher, HTMLStencilElement {
    }
    var HTMLSmcLauncherElement: {
        prototype: HTMLSmcLauncherElement;
        new (): HTMLSmcLauncherElement;
    };
    interface HTMLSmcMarkdownElement extends Components.SmcMarkdown, HTMLStencilElement {
    }
    var HTMLSmcMarkdownElement: {
        prototype: HTMLSmcMarkdownElement;
        new (): HTMLSmcMarkdownElement;
    };
    interface HTMLSmcMessageElement extends Components.SmcMessage, HTMLStencilElement {
    }
    var HTMLSmcMessageElement: {
        prototype: HTMLSmcMessageElement;
        new (): HTMLSmcMessageElement;
    };
    interface HTMLSmcMessageListElement extends Components.SmcMessageList, HTMLStencilElement {
    }
    var HTMLSmcMessageListElement: {
        prototype: HTMLSmcMessageListElement;
        new (): HTMLSmcMessageListElement;
    };
    interface HTMLSmcPreChatFormElement extends Components.SmcPreChatForm, HTMLStencilElement {
    }
    var HTMLSmcPreChatFormElement: {
        prototype: HTMLSmcPreChatFormElement;
        new (): HTMLSmcPreChatFormElement;
    };
    interface HTMLSmcQuickRepliesElementEventMap {
        "smcQuickReply": { text: string };
    }
    interface HTMLSmcQuickRepliesElement extends Components.SmcQuickReplies, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSmcQuickRepliesElementEventMap>(type: K, listener: (this: HTMLSmcQuickRepliesElement, ev: SmcQuickRepliesCustomEvent<HTMLSmcQuickRepliesElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSmcQuickRepliesElementEventMap>(type: K, listener: (this: HTMLSmcQuickRepliesElement, ev: SmcQuickRepliesCustomEvent<HTMLSmcQuickRepliesElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSmcQuickRepliesElement: {
        prototype: HTMLSmcQuickRepliesElement;
        new (): HTMLSmcQuickRepliesElement;
    };
    interface HTMLSmcTimestampElement extends Components.SmcTimestamp, HTMLStencilElement {
    }
    var HTMLSmcTimestampElement: {
        prototype: HTMLSmcTimestampElement;
        new (): HTMLSmcTimestampElement;
    };
    interface HTMLSmcTypingIndicatorElement extends Components.SmcTypingIndicator, HTMLStencilElement {
    }
    var HTMLSmcTypingIndicatorElement: {
        prototype: HTMLSmcTypingIndicatorElement;
        new (): HTMLSmcTypingIndicatorElement;
    };
    interface HTMLElementTagNameMap {
        "smc-chat-widget": HTMLSmcChatWidgetElement;
        "smc-chat-window": HTMLSmcChatWindowElement;
        "smc-feedback": HTMLSmcFeedbackElement;
        "smc-header": HTMLSmcHeaderElement;
        "smc-input-bar": HTMLSmcInputBarElement;
        "smc-launcher": HTMLSmcLauncherElement;
        "smc-markdown": HTMLSmcMarkdownElement;
        "smc-message": HTMLSmcMessageElement;
        "smc-message-list": HTMLSmcMessageListElement;
        "smc-pre-chat-form": HTMLSmcPreChatFormElement;
        "smc-quick-replies": HTMLSmcQuickRepliesElement;
        "smc-timestamp": HTMLSmcTimestampElement;
        "smc-typing-indicator": HTMLSmcTypingIndicatorElement;
    }
}
declare namespace LocalJSX {
    type OneOf<K extends string, PropT, AttrT = PropT> = { [P in K]: PropT } & { [P in `attr:${K}` | `prop:${K}`]?: never } | { [P in `attr:${K}`]: AttrT } & { [P in K | `prop:${K}`]?: never } | { [P in `prop:${K}`]: PropT } & { [P in K | `attr:${K}`]?: never };

    interface SmcChatWidget {
        "apiUrl"?: string;
        "sdkId": string;
    }
    interface SmcChatWindow {
    }
    interface SmcFeedback {
        "messageId": string;
    }
    interface SmcHeader {
    }
    interface SmcInputBar {
    }
    interface SmcLauncher {
    }
    interface SmcMarkdown {
        "content": string;
    }
    interface SmcMessage {
        "content": string;
        "messageId": string;
        "role": 'user' | 'assistant';
        "status"?: string;
        "timestamp": string;
    }
    interface SmcMessageList {
    }
    interface SmcPreChatForm {
    }
    interface SmcQuickReplies {
        "onSmcQuickReply"?: (event: SmcQuickRepliesCustomEvent<{ text: string }>) => void;
    }
    interface SmcTimestamp {
        "timestamp": string;
    }
    interface SmcTypingIndicator {
    }

    interface SmcChatWidgetAttributes {
        "sdkId": string;
        "apiUrl": string;
    }
    interface SmcFeedbackAttributes {
        "messageId": string;
    }
    interface SmcMarkdownAttributes {
        "content": string;
    }
    interface SmcMessageAttributes {
        "content": string;
        "role": 'user' | 'assistant';
        "timestamp": string;
        "messageId": string;
        "status": string;
    }
    interface SmcTimestampAttributes {
        "timestamp": string;
    }

    interface IntrinsicElements {
        "smc-chat-widget": Omit<SmcChatWidget, keyof SmcChatWidgetAttributes> & { [K in keyof SmcChatWidget & keyof SmcChatWidgetAttributes]?: SmcChatWidget[K] } & { [K in keyof SmcChatWidget & keyof SmcChatWidgetAttributes as `attr:${K}`]?: SmcChatWidgetAttributes[K] } & { [K in keyof SmcChatWidget & keyof SmcChatWidgetAttributes as `prop:${K}`]?: SmcChatWidget[K] } & OneOf<"sdkId", SmcChatWidget["sdkId"], SmcChatWidgetAttributes["sdkId"]>;
        "smc-chat-window": SmcChatWindow;
        "smc-feedback": Omit<SmcFeedback, keyof SmcFeedbackAttributes> & { [K in keyof SmcFeedback & keyof SmcFeedbackAttributes]?: SmcFeedback[K] } & { [K in keyof SmcFeedback & keyof SmcFeedbackAttributes as `attr:${K}`]?: SmcFeedbackAttributes[K] } & { [K in keyof SmcFeedback & keyof SmcFeedbackAttributes as `prop:${K}`]?: SmcFeedback[K] } & OneOf<"messageId", SmcFeedback["messageId"], SmcFeedbackAttributes["messageId"]>;
        "smc-header": SmcHeader;
        "smc-input-bar": SmcInputBar;
        "smc-launcher": SmcLauncher;
        "smc-markdown": Omit<SmcMarkdown, keyof SmcMarkdownAttributes> & { [K in keyof SmcMarkdown & keyof SmcMarkdownAttributes]?: SmcMarkdown[K] } & { [K in keyof SmcMarkdown & keyof SmcMarkdownAttributes as `attr:${K}`]?: SmcMarkdownAttributes[K] } & { [K in keyof SmcMarkdown & keyof SmcMarkdownAttributes as `prop:${K}`]?: SmcMarkdown[K] } & OneOf<"content", SmcMarkdown["content"], SmcMarkdownAttributes["content"]>;
        "smc-message": Omit<SmcMessage, keyof SmcMessageAttributes> & { [K in keyof SmcMessage & keyof SmcMessageAttributes]?: SmcMessage[K] } & { [K in keyof SmcMessage & keyof SmcMessageAttributes as `attr:${K}`]?: SmcMessageAttributes[K] } & { [K in keyof SmcMessage & keyof SmcMessageAttributes as `prop:${K}`]?: SmcMessage[K] } & OneOf<"content", SmcMessage["content"], SmcMessageAttributes["content"]> & OneOf<"role", SmcMessage["role"], SmcMessageAttributes["role"]> & OneOf<"timestamp", SmcMessage["timestamp"], SmcMessageAttributes["timestamp"]> & OneOf<"messageId", SmcMessage["messageId"], SmcMessageAttributes["messageId"]>;
        "smc-message-list": SmcMessageList;
        "smc-pre-chat-form": SmcPreChatForm;
        "smc-quick-replies": SmcQuickReplies;
        "smc-timestamp": Omit<SmcTimestamp, keyof SmcTimestampAttributes> & { [K in keyof SmcTimestamp & keyof SmcTimestampAttributes]?: SmcTimestamp[K] } & { [K in keyof SmcTimestamp & keyof SmcTimestampAttributes as `attr:${K}`]?: SmcTimestampAttributes[K] } & { [K in keyof SmcTimestamp & keyof SmcTimestampAttributes as `prop:${K}`]?: SmcTimestamp[K] } & OneOf<"timestamp", SmcTimestamp["timestamp"], SmcTimestampAttributes["timestamp"]>;
        "smc-typing-indicator": SmcTypingIndicator;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "smc-chat-widget": LocalJSX.IntrinsicElements["smc-chat-widget"] & JSXBase.HTMLAttributes<HTMLSmcChatWidgetElement>;
            "smc-chat-window": LocalJSX.IntrinsicElements["smc-chat-window"] & JSXBase.HTMLAttributes<HTMLSmcChatWindowElement>;
            "smc-feedback": LocalJSX.IntrinsicElements["smc-feedback"] & JSXBase.HTMLAttributes<HTMLSmcFeedbackElement>;
            "smc-header": LocalJSX.IntrinsicElements["smc-header"] & JSXBase.HTMLAttributes<HTMLSmcHeaderElement>;
            "smc-input-bar": LocalJSX.IntrinsicElements["smc-input-bar"] & JSXBase.HTMLAttributes<HTMLSmcInputBarElement>;
            "smc-launcher": LocalJSX.IntrinsicElements["smc-launcher"] & JSXBase.HTMLAttributes<HTMLSmcLauncherElement>;
            "smc-markdown": LocalJSX.IntrinsicElements["smc-markdown"] & JSXBase.HTMLAttributes<HTMLSmcMarkdownElement>;
            "smc-message": LocalJSX.IntrinsicElements["smc-message"] & JSXBase.HTMLAttributes<HTMLSmcMessageElement>;
            "smc-message-list": LocalJSX.IntrinsicElements["smc-message-list"] & JSXBase.HTMLAttributes<HTMLSmcMessageListElement>;
            "smc-pre-chat-form": LocalJSX.IntrinsicElements["smc-pre-chat-form"] & JSXBase.HTMLAttributes<HTMLSmcPreChatFormElement>;
            "smc-quick-replies": LocalJSX.IntrinsicElements["smc-quick-replies"] & JSXBase.HTMLAttributes<HTMLSmcQuickRepliesElement>;
            "smc-timestamp": LocalJSX.IntrinsicElements["smc-timestamp"] & JSXBase.HTMLAttributes<HTMLSmcTimestampElement>;
            "smc-typing-indicator": LocalJSX.IntrinsicElements["smc-typing-indicator"] & JSXBase.HTMLAttributes<HTMLSmcTypingIndicatorElement>;
        }
    }
}
