/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SmcChatWidget {
        "apiUrl"?: string;
        "sdkId": string;
    }
    interface SmcChatWindow {
    }
    interface SmcHeader {
    }
    interface SmcLauncher {
    }
}
declare global {
    interface HTMLSmcChatWidgetElement extends Components.SmcChatWidget, HTMLStencilElement {
    }
    var HTMLSmcChatWidgetElement: {
        prototype: HTMLSmcChatWidgetElement;
        new (): HTMLSmcChatWidgetElement;
    };
    interface HTMLSmcChatWindowElement extends Components.SmcChatWindow, HTMLStencilElement {
    }
    var HTMLSmcChatWindowElement: {
        prototype: HTMLSmcChatWindowElement;
        new (): HTMLSmcChatWindowElement;
    };
    interface HTMLSmcHeaderElement extends Components.SmcHeader, HTMLStencilElement {
    }
    var HTMLSmcHeaderElement: {
        prototype: HTMLSmcHeaderElement;
        new (): HTMLSmcHeaderElement;
    };
    interface HTMLSmcLauncherElement extends Components.SmcLauncher, HTMLStencilElement {
    }
    var HTMLSmcLauncherElement: {
        prototype: HTMLSmcLauncherElement;
        new (): HTMLSmcLauncherElement;
    };
    interface HTMLElementTagNameMap {
        "smc-chat-widget": HTMLSmcChatWidgetElement;
        "smc-chat-window": HTMLSmcChatWindowElement;
        "smc-header": HTMLSmcHeaderElement;
        "smc-launcher": HTMLSmcLauncherElement;
    }
}
declare namespace LocalJSX {
    type OneOf<K extends string, PropT, AttrT = PropT> = { [P in K]: PropT } & { [P in `attr:${K}` | `prop:${K}`]?: never } | { [P in `attr:${K}`]: AttrT } & { [P in K | `prop:${K}`]?: never } | { [P in `prop:${K}`]: PropT } & { [P in K | `attr:${K}`]?: never };

    interface SmcChatWidget {
        "apiUrl"?: string;
        "sdkId": string;
    }
    interface SmcChatWindow {
    }
    interface SmcHeader {
    }
    interface SmcLauncher {
    }

    interface SmcChatWidgetAttributes {
        "sdkId": string;
        "apiUrl": string;
    }

    interface IntrinsicElements {
        "smc-chat-widget": Omit<SmcChatWidget, keyof SmcChatWidgetAttributes> & { [K in keyof SmcChatWidget & keyof SmcChatWidgetAttributes]?: SmcChatWidget[K] } & { [K in keyof SmcChatWidget & keyof SmcChatWidgetAttributes as `attr:${K}`]?: SmcChatWidgetAttributes[K] } & { [K in keyof SmcChatWidget & keyof SmcChatWidgetAttributes as `prop:${K}`]?: SmcChatWidget[K] } & OneOf<"sdkId", SmcChatWidget["sdkId"], SmcChatWidgetAttributes["sdkId"]>;
        "smc-chat-window": SmcChatWindow;
        "smc-header": SmcHeader;
        "smc-launcher": SmcLauncher;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "smc-chat-widget": LocalJSX.IntrinsicElements["smc-chat-widget"] & JSXBase.HTMLAttributes<HTMLSmcChatWidgetElement>;
            "smc-chat-window": LocalJSX.IntrinsicElements["smc-chat-window"] & JSXBase.HTMLAttributes<HTMLSmcChatWindowElement>;
            "smc-header": LocalJSX.IntrinsicElements["smc-header"] & JSXBase.HTMLAttributes<HTMLSmcHeaderElement>;
            "smc-launcher": LocalJSX.IntrinsicElements["smc-launcher"] & JSXBase.HTMLAttributes<HTMLSmcLauncherElement>;
        }
    }
}
