image: oven/bun:latest

definitions:
  caches:
    bun: ~/.bun

pipelines:
  pull-requests:
    '**':
      - step: &ci
          name: Lint, Test & Build
          caches:
            - bun
          script:
            - bun install --frozen-lockfile
            - bun run test
            - bun run build
            - bunx playwright install --with-deps chromium
            - bun run e2e
          artifacts:
            - apps/web-ui-e2e/playwright-report/**

  branches:
    main:
      - step: *ci
