config:
  aws:region: us-east-1
  chatbot-compute:appName: chatflow-nonprod
  chatbot-compute:appUrl: https://d28eqq2bj0c0yk.cloudfront.net
  chatbot-compute:subscriptionEmails: ""
encryptionsalt: v1:pXRwNrkJJkA=:v1:vMxn7HXnrtwjJDos:YnYpD6kwJYXYuyHQLtc513Sr8gN2YA==
